In [1]:
import pandas as pd
import json
import re
import geopandas as gpd

In [2]:
def parseJson(jason):
    m = json.loads(jason)['coordinates']
    return m[0], m[1]

In [3]:
parkingMeters_df = pd.read_csv("./data/parking-meters.csv", ";", usecols=["PAY_PHONE", "Geom"])

In [4]:
parkingMeters_df['lat'], parkingMeters_df['lon'] = zip(*parkingMeters_df['Geom'].map(parseJson))
parkingMeters_df.head()

,PAY_PHONE,Geom,lat,lon
0,53202,"{""type"": ""Point"", ""coordinates"": [-123.1165913...",-123.116591,49.264936
1,53118,"{""type"": ""Point"", ""coordinates"": [-123.1162579...",-123.116258,49.264931
2,53063,"{""type"": ""Point"", ""coordinates"": [-123.1159258...",-123.115926,49.264925
3,57841,"{""type"": ""Point"", ""coordinates"": [-123.1018689...",-123.101869,49.258462
4,57077,"{""type"": ""Point"", ""coordinates"": [-123.1386316...",-123.138632,49.258181

In [5]:
meterLocs = gpd.GeoDataFrame(parkingMeters_df, geometry=gpd.points_from_xy(parkingMeters_df.lat, parkingMeters_df.lon)).set_index("PAY_PHONE")
meterLocs.head()

,Geom,lat,lon,geometry
PAY_PHONE,,,,
53202,"{""type"": ""Point"", ""coordinates"": [-123.1165913...",-123.116591,49.264936,POINT (-123.1165913049904 49.26493619901395)
53118,"{""type"": ""Point"", ""coordinates"": [-123.1162579...",-123.116258,49.264931,POINT (-123.1162579767762 49.26493102082964)
53063,"{""type"": ""Point"", ""coordinates"": [-123.1159258...",-123.115926,49.264925,POINT (-123.1159258848753 49.26492549862552)
57841,"{""type"": ""Point"", ""coordinates"": [-123.1018689...",-123.101869,49.258462,POINT (-123.1018689688041 49.25846239478444)
57077,"{""type"": ""Point"", ""coordinates"": [-123.1386316...",-123.138632,49.258181,POINT (-123.1386316376238 49.25818110880651)

In [12]:
payByPhone_df= pd.read_csv("./data/pay-by-phone-parking-august-1-to-26-2017.csv", ";", usecols=["METER", "DATE START", "MINUTES", "VEHICLE TYPE"])

In [13]:
payByPhone_df2= pd.read_csv("./data/no-name1.csv", ";", usecols=["METER", "DATE START", "MINUTES", "VEHICLE TYPE"])

In [14]:
payByPhone_df = pd.concat([payByPhone_df, payByPhone_df2])

In [15]:
payByPhone_df

        METER                 DATE START MINUTES         VEHICLE TYPE
0       56248    2017/08/19 16:11:27 PDT      10                  Car
1       50417    2017/08/19 16:11:33 PDT      24                  Car
2       61535    2017/08/19 16:11:36 PDT      60                  Car
3       53847    2017/08/19 16:11:39 PDT      29                  Car
4       54139    2017/08/19 16:11:42 PDT      15                  Car
5       60153    2017/08/19 16:11:43 PDT      29                  Car
6       56086    2017/08/19 16:11:43 PDT      29  Heavy Goods Vehicle
7       62917    2017/08/19 16:11:48 PDT      60                  Car
8       65883    2017/08/19 16:11:52 PDT       5                  Car
9       56492    2017/08/19 16:11:53 PDT      20                  Car
10      56120    2017/08/19 16:11:57 PDT      20                  Car
11      61989    2017/08/19 16:12:00 PDT      60                  Car
12      50756    2017/08/19 16:12:01 PDT      20                  Car
13      64253    2017/08/19 16:12:03 PDT      10                  Car
14      62306    2017/08/19 16:12:08 PDT      24                  Car
15      65658    2017/08/19 16:12:08 PDT      29                  Car
16      53055    2017/08/19 16:12:20 PDT     180                  Car
17      65877    2017/08/19 16:12:22 PDT     120                  Car
18      51597    2017/08/19 16:12:28 PDT      10                  Car
19      51897    2017/08/19 16:12:37 PDT      20                  Car
20      56110    2017/08/19 16:12:39 PDT      45                  Car
21      50072    2017/08/19 16:12:48 PDT      60                  Car
22      60916    2017/08/19 16:12:56 PDT      15                  Car
23      61846    2017/08/19 16:12:58 PDT      60                  Car
24      61108    2017/08/19 16:13:16 PDT      29                  Car
25      60359    2017/08/19 16:13:30 PDT      60                  Car
26      50576    2017/08/19 16:13:37 PDT      29                  Car
27      53521    2017/08/19 16:13:43 PDT      29                  Car
28      54863    2017/08/19 16:13:47 PDT      60                  Car
29      51562    2017/08/19 16:13:53 PDT      29                  Car
...       ...                        ...     ...                  ...
171909  66005  2017-08-31T13:43:58-07:00      10                  Car
171910  52808  2017-08-31T13:44:03-07:00      29                  Car
171911  54767  2017-08-31T13:44:08-07:00      60                  Car
171912  50989  2017-08-31T13:44:16-07:00      20                  Car
171913  65129  2017-08-31T13:44:25-07:00      75                  Car
171914  65682  2017-08-31T13:44:29-07:00      60                  Car
171915  63540  2017-08-31T13:44:31-07:00      60                  Car
171916  53277  2017-08-31T13:44:33-07:00      60                  Car
171917  56377  2017-08-31T13:44:47-07:00      60                  Car
171918  63524  2017-08-31T13:44:59-07:00      60                  Car
171919  65076  2017-08-31T13:45:07-07:00      29                  Car
171920  50654  2017-08-31T13:45:17-07:00      10                  Car
171921  51135  2017-08-31T13:45:39-07:00      24                  Car
171922  60305  2017-08-31T13:45:48-07:00      75                  Car
171923  63986  2017-08-31T13:45:55-07:00      15                  Car
171924  53332  2017-08-31T13:46:05-07:00      73                  Car
171925  63293  2017-08-31T13:46:21-07:00      60                  Car
171926  60223  2017-08-31T13:46:23-07:00      60                  Car
171927  64721  2017-08-31T13:46:25-07:00      73                  Car
171928  52897  2017-08-31T13:46:29-07:00      60                  Car
171929  60188  2017-08-31T13:46:35-07:00      10                  Car
171930  62340  2017-08-31T13:46:38-07:00      60                  Car
171931  64293  2017-08-31T13:46:46-07:00      15                  Car
171932  56342  2017-08-31T13:46:54-07:00      60                  Car
171933  62343  2017-08-31T13:47:17-07:00      75                  Car
171934  54644  2017-08-31T13:47:29-07:00      72                  Car
171935  69999  2017-08-31T13:47:49-07:00      24                  Car
171936  62651  2017-08-31T13:47:56-07:00      20                  Car
171937  69999  2017-08-31T13:47:57-07:00      10                  Car
171938  63712  2017-08-31T13:48:02-07:00      20                  Car

[1474193 rows x 4 columns]

In [16]:
data = payByPhone_df.join(meterLocs, 'METER').dropna()
data

,METER,DATE START,MINUTES,VEHICLE TYPE,Geom,lat,lon,geometry
0,56248,2017/08/19 16:11:27 PDT,10,Car,"{""type"": ""Point"", ""coordinates"": [-123.1013519...",-123.101352,49.256948,POINT (-123.1013519684208 49.2569478933431)
1,50417,2017/08/19 16:11:33 PDT,24,Car,"{""type"": ""Point"", ""coordinates"": [-123.0695043...",-123.069504,49.269223,POINT (-123.0695043511682 49.26922338817577)
2,61535,2017/08/19 16:11:36 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1194983...",-123.119498,49.284242,POINT (-123.1194983612811 49.28424189777076)
3,53847,2017/08/19 16:11:39 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.0692730...",-123.069273,49.272092,POINT (-123.069273088353 49.27209226521855)
4,54139,2017/08/19 16:11:42 PDT,15,Car,"{""type"": ""Point"", ""coordinates"": [-123.1433195...",-123.143320,49.263274,POINT (-123.1433195538048 49.26327413595527)
5,60153,2017/08/19 16:11:43 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1165633...",-123.116563,49.279777,POINT (-123.1165633021756 49.2797773957969)
6,56086,2017/08/19 16:11:43 PDT,29,Heavy Goods Vehicle,"{""type"": ""Point"", ""coordinates"": [-123.1506061...",-123.150606,49.263989,POINT (-123.1506061795238 49.26398870306416)
7,62917,2017/08/19 16:11:48 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1150983...",-123.115098,49.279307,POINT (-123.1150983665901 49.27930697706518)
8,65883,2017/08/19 16:11:52 PDT,5,Car,"{""type"": ""Point"", ""coordinates"": [-123.1148950...",-123.114895,49.283237,POINT (-123.1148950201017 49.28323724498659)
9,56492,2017/08/19 16:11:53 PDT,20,Car,"{""type"": ""Point"", ""coordinates"": [-123.0332676...",-123.033268,49.232936,POINT (-123.0332676562367 49.23293578903827)
10,56120,2017/08/19 16:11:57 PDT,20,Car,"{""type"": ""Point"", ""coordinates"": [-123.1570029...",-123.157003,49.263986,POINT (-123.1570029683644 49.26398578286377)
11,61989,2017/08/19 16:12:00 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1246735...",-123.124674,49.273981,POINT (-123.1246735519441 49.27398062655585)
12,50756,2017/08/19 16:12:01 PDT,20,Car,"{""type"": ""Point"", ""coordinates"": [-123.1567567...",-123.156757,49.234528,POINT (-123.1567567515326 49.2345276528302)
13,64253,2017/08/19 16:12:03 PDT,10,Car,"{""type"": ""Point"", ""coordinates"": [-123.1091897...",-123.109190,49.283107,POINT (-123.1091897564798 49.28310690479915)
14,62306,2017/08/19 16:12:08 PDT,24,Car,"{""type"": ""Point"", ""coordinates"": [-123.1237017...",-123.123702,49.276330,POINT (-123.1237017994334 49.27632955016077)
15,65658,2017/08/19 16:12:08 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1247927...",-123.124793,49.275609,POINT (-123.1247927952298 49.27560902289223)
16,53055,2017/08/19 16:12:20 PDT,180,Car,"{""type"": ""Point"", ""coordinates"": [-123.1413495...",-123.141350,49.270653,POINT (-123.1413495980041 49.270652988592)
17,65877,2017/08/19 16:12:22 PDT,120,Car,"{""type"": ""Point"", ""coordinates"": [-123.1250066...",-123.125007,49.279323,POINT (-123.1250066139396 49.27932325454013)
18,51597,2017/08/19 16:12:28 PDT,10,Car,"{""type"": ""Point"", ""coordinates"": [-123.1707357...",-123.170736,49.264198,POINT (-123.1707357582182 49.264197563722)
19,51897,2017/08/19 16:12:37 PDT,20,Car,"{""type"": ""Point"", ""coordinates"": [-123.1168811...",-123.116881,49.264219,POINT (-123.116881155993 49.264218988332)
20,56110,2017/08/19 16:12:39 PDT,45,Car,"{""type"": ""Point"", ""coordinates"": [-123.1640802...",-123.164080,49.263918,POINT (-123.1640802066391 49.26391751630873)
21,50072,2017/08/19 16:12:48 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1282518...",-123.128252,49.263546,POINT (-123.1282518538963 49.26354614735917)
22,60916,2017/08/19 16:12:56 PDT,15,Car,"{""type"": ""Point"", ""coordinates"": [-123.1189778...",-123.118978,49.279454,POINT (-123.1189778728274 49.27945407671438)
23,61846,2017/08/19 16:12:58 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1234524...",-123.123452,49.277381,POINT (-123.1234524894284 49.2773813180623)
24,61108,2017/08/19 16:13:16 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.0992038...",-123.099204,49.283121,POINT (-123.0992038308034 49.28312063181946)
25,60359,2017/08/19 16:13:30 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1232266...",-123.123227,49.273679,POINT (-123.1232266719982 49.27367858197454)
26,50576,2017/08/19 16:13:37 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1470790...",-123.147079,49.268127,POINT (-123.1470790177366 49.26812667811388)
27,53521,2017/08/19 16:13:43 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1384684...",-123.138468,49.262481,POINT (-123.1384684009141 49.2624809172773)
28,54863,2017/08/19 16:13:47 PDT,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1014978...",-123.101498,49.247281,POINT (-123.1014978848031 49.24728060726416)
29,51562,2017/08/19 16:13:53 PDT,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.0694121...",-123.069412,49.275241,POINT (-123.069412144372 49.27524112755792)
...,...,...,...,...,...,...,...,...
65505,63423,2017-08-28T05:48:57-07:00,10,Car,"{""type"": ""Point"", ""coordinates"": [-123.1185500...",-123.118550,49.275855,POINT (-123.1185500652181 49.27585465255223)
65506,56217,2017-08-28T05:49:02-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1012759...",-123.101276,49.259098,POINT (-123.1012759718999 49.25909772630032)
65507,54159,2017-08-28T05:49:02-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1473797...",-123.147380,49.270631,POINT (-123.1473797466672 49.27063133191907)
65508,61170,2017-08-28T05:49:04-07:00,35,Car,"{""type"": ""Point"", ""coordinates"": [-123.1032892...",-123.103289,49.283496,POINT (-123.1032892861221 49.28349632473289)
65509,51023,2017-08-28T05:49:05-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1385866...",-123.138587,49.259404,POINT (-123.1385866458145 49.25940441309004)
65510,60311,2017-08-28T05:49:13-07:00,24,Car,"{""type"": ""Point"", ""coordinates"": [-123.1208460...",-123.120846,49.278219,POINT (-123.1208460428538 49.27821910535377)
65511,51324,2017-08-28T05:49:15-07:00,90,Heavy Goods Vehicle,"{""type"": ""Point"", ""coordinates"": [-123.1344713...",-123.134471,49.264389,POINT (-123.1344713120297 49.26438942015446)
65512,52389,2017-08-28T05:49:22-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1433399...",-123.143340,49.267458,POINT (-123.1433399187581 49.26745778058222)
65513,50182,2017-08-28T05:49:24-07:00,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1257984...",-123.125798,49.263510,POINT (-123.1257984866931 49.26350979639327)
65514,60764,2017-08-28T05:49:27-07:00,15,Car,"{""type"": ""Point"", ""coordinates"": [-123.1233529...",-123.123353,49.280246,POINT (-123.1233529725456 49.28024574247072)
65515,63472,2017-08-28T05:49:28-07:00,90,Car,"{""type"": ""Point"", ""coordinates"": [-123.1296623...",-123.129662,49.281316,POINT (-123.1296623935813 49.28131625947931)
65516,51345,2017-08-28T05:49:34-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1071256...",-123.107126,49.263866,POINT (-123.10712564467 49.26386625320226)
65517,61089,2017-08-28T05:49:35-07:00,75,Car,"{""type"": ""Point"", ""coordinates"": [-123.1059363...",-123.105936,49.282847,POINT (-123.1059363658306 49.28284677037944)
65518,61363,2017-08-28T05:49:45-07:00,45,Car,"{""type"": ""Point"", ""coordinates"": [-123.1210612...",-123.121061,49.275155,POINT (-123.1210612040163 49.27515529961472)
65519,63412,2017-08-28T05:49:45-07:00,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1161392...",-123.116139,49.286463,POINT (-123.1161392366389 49.2864629835575)
65521,62234,2017-08-28T05:49:53-07:00,90,Car,"{""type"": ""Point"", ""coordinates"": [-123.1203471...",-123.120347,49.288636,POINT (-123.1203471403693 49.28863627328852)
65522,65968,2017-08-28T05:50:00-07:00,120,Car,"{""type"": ""Point"", ""coordinates"": [-123.1255488...",-123.125549,49.286568,POINT (-123.125548869762 49.28656823643769)
65523,64457,2017-08-28T05:50:03-07:00,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1259726...",-123.125973,49.285439,POINT (-123.1259726729075 49.28543903405208)
65524,50069,2017-08-28T05:50:04-07:00,29,Car,"{""type"": ""Point"", ""coordinates"": [-123.1261557...",-123.126156,49.263516,POINT (-123.1261557242666 49.26351588343639)
65525,56224,2017-08-28T05:50:06-07:00,115,Car,"{""type"": ""Point"", ""coordinates"": [-123.0990368...",-123.099037,49.263073,POINT (-123.0990368441752 49.26307290539709)
65526,64328,2017-08-28T05:50:10-07:00,20,Car,"{""type"": ""Point"", ""coordinates"": [-123.1208711...",-123.120871,49.279464,POINT (-123.1208711235742 49.27946373357225)
65527,52695,2017-08-28T05:50:12-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1415077...",-123.141508,49.263557,POINT (-123.1415077335456 49.26355692972069)
65528,54621,2017-08-28T05:50:13-07:00,120,Car,"{""type"": ""Point"", ""coordinates"": [-123.1573581...",-123.157358,49.234673,POINT (-123.1573581748104 49.23467331388942)
65529,60217,2017-08-28T05:50:15-07:00,15,Car,"{""type"": ""Point"", ""coordinates"": [-123.1214785...",-123.121479,49.281486,POINT (-123.1214785330313 49.28148649943852)
65530,61438,2017-08-28T05:50:16-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1197062...",-123.119706,49.280235,POINT (-123.1197062200578 49.28023494274746)
65531,64324,2017-08-28T05:50:19-07:00,5,Car,"{""type"": ""Point"", ""coordinates"": [-123.0987381...",-123.098738,49.279532,POINT (-123.0987381427847 49.27953180176164)
65532,55003,2017-08-28T05:50:19-07:00,120,Car,"{""type"": ""Point"", ""coordinates"": [-123.1012895...",-123.101290,49.247475,POINT (-123.1012895573081 49.24747526699743)
65533,63907,2017-08-28T05:50:21-07:00,15,Car,"{""type"": ""Point"", ""coordinates"": [-123.1253128...",-123.125313,49.278950,POINT (-123.1253128070998 49.27895006357051)
65534,56597,2017-08-28T05:50:21-07:00,60,Car,"{""type"": ""Point"", ""coordinates"": [-123.1862915...",-123.186292,49.263564,POINT (-123.1862915556389 49.26356363635407)
65535,64046,2017-08-28T05:50:27-07:00,90,Car,"{""type"": ""Point"", ""coordinates"": [-123.1322820...",-123.132282,49.290732,POINT (-123.1322820356963 49.29073164928233)

In [17]:
aggdata = data.groupby('METER').agg('count')
aggdata

       DATE START  MINUTES  VEHICLE TYPE  Geom   lat   lon  geometry
METER
50001          61       61            61    61    61    61        61
50002         149      149           149   149   149   149       149
50003         135      135           135   135   135   135       135
50004          73       73            73    73    73    73        73
50005          58       58            58    58    58    58        58
50006         209      209           209   209   209   209       209
50007         247      247           247   247   247   247       247
50008          12       12            12    12    12    12        12
50009         111      111           111   111   111   111       111
50010          83       83            83    83    83    83        83
50011          71       71            71    71    71    71        71
50013          61       61            61    61    61    61        61
50014          52       52            52    52    52    52        52
50015          57       57            57    57    57    57        57
50016          39       39            39    39    39    39        39
50017          63       63            63    63    63    63        63
50018         137      137           137   137   137   137       137
50019         146      146           146   146   146   146       146
50020         191      191           191   191   191   191       191
50021          87       87            87    87    87    87        87
50022         241      241           241   241   241   241       241
50023          50       50            50    50    50    50        50
50024          91       91            91    91    91    91        91
50025          26       26            26    26    26    26        26
50027          57       57            57    57    57    57        57
50028         102      102           102   102   102   102       102
50029         128      128           128   128   128   128       128
50030         123      123           123   123   123   123       123
50031         158      158           158   158   158   158       158
50032         146      146           146   146   146   146       146
...           ...      ...           ...   ...   ...   ...       ...
67955          25       25            25    25    25    25        25
67956          56       56            56    56    56    56        56
67957          13       13            13    13    13    13        13
67958         131      131           131   131   131   131       131
67959           6        6             6     6     6     6         6
67962          53       53            53    53    53    53        53
67991           4        4             4     4     4     4         4
67992          25       25            25    25    25    25        25
67998          39       39            39    39    39    39        39
68856          34       34            34    34    34    34        34
69943         375      375           375   375   375   375       375
69944        1091     1091          1091  1091  1091  1091      1091
69945         575      575           575   575   575   575       575
69946         603      603           603   603   603   603       603
69947        1541     1541          1541  1541  1541  1541      1541
69948         458      458           458   458   458   458       458
69961         485      485           485   485   485   485       485
69962         785      785           785   785   785   785       785
69963         787      787           787   787   787   787       787
69964         469      469           469   469   469   469       469
69966         375      375           375   375   375   375       375
69967         780      780           780   780   780   780       780
69968         737      737           737   737   737   737       737
69969        1213     1213          1213  1213  1213  1213      1213
69985         950      950           950   950   950   950       950
69986         909      909           909   909   909   909       909
69987         753      753           753   753   753   753       753
69988        1136     1136          1136  1136  1136  1136      1136
69989        1547     1547          1547  1547  1547  1547      1547
69999        2735     2735          2735  2735  2735  2735      2735

[9402 rows x 7 columns]